title: ЧЕРВЕПЕДИЯ
description: Официальный вестник Черветреда.
email:
baseurl: ""
url: "https://chervepediya.github.io"
paginate: 5
paginate_path: "/page:num/"

# Настройки меню
navigation:
  - title: Главная
    url: /
  - title: Черветред
    url: /chervethread/
  - title: Манифест
    url: /manifest/
  - title: О нас
    url: /about/

# Social media links
social:
  telegram: https://t.me/chervethreadofficial
  youtube: https://youtube.com/@первый_черванский
  twitter: https://twitter.com/chervethread

# Geo tags
geo:
  country: россия
  city: москва

# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

  - name: generate-sitemap
    uses: cicirello/generate-sitemap@v1.10.1

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# SEO Settings
keywords: Черветред, Червепедия, Двач, Кинаман, Dr. Crow, создатель черветреда, Червепедия
author: Червепедия

defaults:
  -
    scope:
      path: ""
    values:
      image:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /:title/