title: Червепедия
description: Черветред - антироссийский тред на Дваче, созданный для обсуждения мемов, культуры и протестных настроений в анонимной среде.
baseurl: ""
url: "https://chervepediya.github.io"
header_pages:
  - index.md: home
  - about.md: user
  - contact.md: envelope
  - archive.md: archive
  - manifest.md: file-alt
paginate: 5
paginate_path: "/page:num/"
