# Основные настройки
title: Червепедия
description: Официальный вестник черветреда. Черветред - антироссийский тред на дваче.
url: ""  # Абсолютный URL 
baseurl: ""  #
timezone: Europe/Moscow
lang: ru

# Настройки пагинации
paginate: 5  # Количество постов на странице
paginate_path: "/page:num/"  # Шаблон URL для страниц пагинации

# Плагины для GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Меню с иконками
menu:
  - title: Главная
    url: "/"
    icon: "fas fa-home"
  - title: Черветред
    url: "/chervethread/"
    icon: "fas fa-user"
  - title: Контакты
    url: "#footer"
    icon: "fas fa-envelope"
  - title: Архив
    url: "/archive/"
    icon: "fas fa-archive"
  - title: Манифест Черветреда
    url: "/manifest/"
    icon: "fas fa-file-alt"
