title: ЧЕРВЕПЕДИЯ
description: Вестник Черветреда. Хранилище фольклора черванов.
email: your-email@example.com
baseurl: "https://chervepediya.github.io/"
url: ""
paginate: 5
paginate_path: "/page:num/"

# Настройки меню
navigation:
  - title: Главная
    url: /
  - title: Черветред
    url: /chervethread/
  - title: Манифест
    url: /manifest/
  - title: О нас
    url: /about/

# Social media links
social:
  telegram: https://t.me/your_telegram
  youtube: https://youtube.com/@your_youtube
  twitter: https://twitter.com/your_twitter

# Geo tags
geo:
  country: россия
  city: москва

# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap


include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# SEO Settings
keywords: Черветред, Червепедия, Двач, Кинаман, Dr. Crow, создатель черветреда, Червепедия
author: Червепедия

defaults:
  -
    scope:
      path: ""
    values:
      image:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: /:title/
